# Generated by Django 3.0 on 2022-05-11 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contato',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_completo', models.CharField(max_length=194, verbose_name='Nome Completo')),
                ('email', models.EmailField(max_length=194, unique=True, verbose_name='E-mail do usuário')),
                ('telefone', models.CharField(max_length=11, verbose_name='Numero de Telefone')),
                ('motivo', models.CharField(max_length=150, verbose_name='Motivo da mensagem')),
                ('mensagem', models.CharField(max_length=100, verbose_name='Mensagem')),
                ('data', models.DateField(auto_now_add=True, verbose_name='Data da Mensagem')),
            ],
            options={
                'verbose_name': 'Contato',
                'verbose_name_plural': 'Contatos',
                'db_table': 'contato',
            },
        ),
    ]
