# Generated by Django 3.0 on 2022-05-11 20:36

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('livros', '0003_auto_20220502_0837'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reseva',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(auto_now_add=True, verbose_name='Data da Mensagem')),
                ('livro', models.ManyToManyField(to='livros.Livro', verbose_name='Livro')),
                ('usuario', models.ManyToManyField(to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Reserva',
                'verbose_name_plural': 'Reservas',
                'db_table': 'reserva',
            },
        ),
    ]
