# Generated by Django 3.0 on 2022-04-17 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Livro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=120, verbose_name='Titulo do livro')),
                ('nome_autor', models.CharField(max_length=194, verbose_name='Autor do livro')),
                ('imagem_capa', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Imagem de capa do livro')),
                ('ano_publicacao', models.DateField(verbose_name='Ano de publicação')),
                ('genero', models.TextField(max_length=60, verbose_name='Gênero literário')),
                ('numero_exemplares', models.PositiveSmallIntegerField(verbose_name='Quantidade de exemplares disponiveis')),
            ],
            options={
                'verbose_name': 'Livro',
                'verbose_name_plural': 'Livros',
                'db_table': 'visitantes',
            },
        ),
    ]
