# Generated by Django 3.0 on 2022-04-18 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livros', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='livro',
            name='descricao',
            field=models.TextField(default=1, max_length=250, verbose_name='Resenha do livro'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='livro',
            name='genero',
            field=models.CharField(max_length=60, verbose_name='Gênero literário'),
        ),
        migrations.AlterModelTable(
            name='livro',
            table='livro',
        ),
    ]
